# Generated by Django 4.0.1 on 2022-01-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=2, verbose_name='Sigla')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('region', models.CharField(max_length=50, verbose_name='Região')),
            ],
            options={
                'verbose_name': 'States',
                'verbose_name_plural': 'Statess',
            },
        ),
    ]
