# Generated by Django 4.0.1 on 2022-01-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
