# Generated by Django 4.0.1 on 2022-01-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_alter_state_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cod_ibge_m', models.IntegerField(verbose_name='Cód. IBGE')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio', to='state.state', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
    ]
