# Generated by Django 4.0.1 on 2022-01-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_municipality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',), 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
