# Generated by Django 4.0.1 on 2022-01-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_alter_state_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('name',), 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
    ]
